### ISSUE TITLE
Uncaught TypeError: this.service.isBasicType is not a function

### ISSUE THREAD

**Issue by Olmer1st** [Gert-dev/php-integrator-navigation#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.2
**System**: Ubuntu 15.10
**Thrown From**: [php-integrator-navigation](https://github.com/Gert-dev/php-integrator-navigation) package, v0.2.2

### Stack Trace

Uncaught TypeError: this.service.isBasicType is not a function

```
At /home/vadim/.atom/packages/php-integrator-navigation/lib/ClassProvider.coffee:188

TypeError: this.service.isBasicType is not a function
    at ClassProvider.module.exports.ClassProvider.addMarkerToCommentLine (/home/vadim/.atom/packages/php-integrator-navigation/lib/ClassProvider.coffee:188:46)
    at ClassProvider.module.exports.ClassProvider.registerMarkers (/home/vadim/.atom/packages/php-integrator-navigation/lib/ClassProvider.coffee:135:18)
    at /home/vadim/.atom/packages/php-integrator-navigation/lib/ClassProvider.coffee:39:14
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:282:9)
    at ClassProvider.module.exports.ClassProvider.activate (/home/vadim/.atom/packages/php-integrator-navigation/lib/ClassProvider.coffee:35:24)
    at Object.module.exports.activateProviders (/home/vadim/.atom/packages/php-integrator-navigation/lib/Main.coffee:38:22)
    at Object.module.exports.setService (/home/vadim/.atom/packages/php-integrator-navigation/lib/Main.coffee:55:10)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/mnt/Data/Projects",
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.1
atom-html-preview, v0.1.13
atom-ternjs, v0.8.4
autoclose-html, v0.19.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v0.10.4
color-picker, v2.0.13
data-atom, v0.15.2
emmet, v2.3.14
file-icons, v1.6.11
highlight-line, v0.11.0
javascript-object-snippets, v0.3.0
javascript-snippets, v1.0.0
js-refactor, v0.6.0
jsformat, v0.9.0
language-mongodb, v0.3.1
minimap, v4.16.1
node-debugger, v1.1.9
nodejs-snippets, v1.1.0
php-debug, v0.1.4
php-integrator-annotations, v0.2.1
php-integrator-autocomplete-plus, v0.2.1
php-integrator-base, v0.2.0
php-integrator-navigation, v0.2.2
php-introspector, v1.0.0
pretty-json, v0.4.1
python-autopep8, v0.1.3
python-tools, v0.6.6
refactor, v0.6.0
rest-client, v0.5.0

# Dev
No dev packages
```

**Comment by glaucomorais** [comment]
This is happening everytime that I save an JavaScript file. It's kind annoying.

**Comment by Gert-dev** [comment]
This should be fixed with version 0.3.0 of the base package, which supplies this method. It seems I was a little too eager with releasing a patch release for this package. If it still happens, feel free to reopen this ticket or reply to it.

**Comment by masterpowers** [comment]
im experiencing this too

**Comment by masterpowers** [comment]
does this plugin only navigate for class? coz its the class only that is working for me 
i cant navigate to the function when i click an implementatioon of this

**Comment by masterpowers** [comment]
Uncaught TypeError: this.service.isBasicType is not a function
/C:/Users/Uriah/.atom/packages/php-integrator-navigation/lib/ClassProvider.coffee:263

**Comment by Gert-dev** [comment]
@masterpowers Have you updated php-integrator-base to 0.3.0?
